### ISSUE TITLE
Implement data refinement

### ISSUE THREAD

**Issue by mk28** [mk28/TINF21C_Team2_AAS_digital_nameplate#10]
Implement methods tha can be called to execute the requests from (Issue #8). 
Further implement methods that can transform the results from the requests to be useful for display in the UI (Issue #9)  and in the generation of QR-Codes.

**Comment by mk28** [comment]
Example JSON for listing all available assets:
```json
{
  "assets":[
    {
      "displayName": "name"
    },
    {
      "displayName": "name2"
    }
  ]
}
```

**Comment by mariskoch** [comment]
#### Current JSON structure
```json
{
  "aaslist": [
    {
      "name": "Festo_3S7PM0CP4BD",
      "iri": "smart.festo.com/demo/aas/1/1/454576463545648365874",
      "url": "/opt/aasx5001/data/01_Festo.aasx"
    }
  ]
}
```

#### Note
Yes, `aaslist` is written in fully small letters. That is how it is returned by the AAS-Server when requesting all assets.

If the majority wants it to be changed to camelCase manually, then it will be.

**Comment by mariskoch** [comment]
This ticket has a deadline for the 09.10.2022. This deadline is now exceeded by one week. Reason for that is, that the workload was larger than anticipated. Two customer questions tickets resulted from this one. The tickets are #42 and #43. As soon as the questions in the given tickets are answered, there will be a follow-up ticket for this one to fully extract all the necessary information for a nameplate.

**Comment by mariskoch** [comment]
ceSign: serverBaseAddress + "server/getfile/" + index + "/aasx/Nameplate/marking_ce.png"
image at <baseAddress>server/getfile/<index>/aasx/Nameplate/marking_ce.png

**Comment by mariskoch** [comment]
Current status of datarefinement:
```json
{
  "assetName": "Bosch_PrecisionModulePSK",
  "manufacturerName": "Bosch Rexroth AG",
  "physicalAddress": {
    "countryCode": "DE",
    "cityTown": "Lohr am Main",
    "zipCode": "97816",
    "street": "Zum Eisengießer 1"
  },
  "serialNumber": "1012160102010001",
  "batchNumber": "00000",
  "manufacturerProductDesignation": "Precision Module PSK",
  "productCountryOfOrigin": "US",
  "yearOfConstruction": "2019",
  "fullNameplate": {<full nameplate here>}
}
```
