### ISSUE TITLE
Nameplate Review

### ISSUE THREAD

**Issue by mariskoch** [mk28/TINF21C_Team2_AAS_digital_nameplate#117]
Dear customer (@mrentsch65),

the nameplates are now visible and ready for download in the asset view. Also, all Servers (admin-shellV1, admin-shellV3, Murrelektronik) are supported. We would appreciate feedback on the namplate design.

### Important
If you want to access the Murrelektronik Server, you need to enable mixed requests in your browser. 

If you want to access the admin-shell servers, make you sure you disable cors (install add-on for that).

**Comment by mrentsch65** [comment]
https://mk28.github.io/TINF21C_Team2_AAS_digital_nameplate/?searchTerm=#/asset/Murrelektronik_V000_PS048_0100001_AAS_SN01234564?server=http%3A%2F%2Faas.murrelektronik.com%3A4001%2Faas

**Why are the following data not fetched from the AAS nameplate submodel?**

![image](https://user-images.githubusercontent.com/50681355/233186814-20ff4e63-8109-4dc0-b38d-6da84142b160.png)

**Comment by MurrTenkeu** [comment]
You need to check also for the new Nameplate Submodel Version:
 https://admin-shell.io/zvei/nameplate/2/0/Nameplate
See this link:
https://github.com/admin-shell-io/submodel-templates/tree/main/published/Digital%20nameplate/2/0
Best Regard Alain

**Comment by mrentsch65** [comment]
Yes, there seems to be a bug regarding the submodel selection:
![image](https://user-images.githubusercontent.com/50681355/233769662-71867deb-b1ac-453c-ac9d-c3d7aaa8301d.png)

**Comment by MurrTenkeu** [comment]
![image](https://user-images.githubusercontent.com/104891811/234040541-b27a5090-cf32-498b-9b2a-0f5994479174.png)



 


The AAS REST API Call  performed by Nameplate Generator provides the response messages result as the AAS REST API Call performed via the firefox web browser, and the data in the response messages(submodels) are also correct. The error occurs during the parsing process of the Submodel Nameplate 

Best regards
Alain

**Comment by mariskoch** [comment]
Dear customer (@mrentsch65),

all 5 remarks of you are implemented and deployed.

> 1. Follow the guidelines in IEC 63365 ch. 5.1.2 "Symbol design" and put in the marking characters "IEC63365" at the bottom of the QR code
> 2. Encode the AssetId as URI on top of the data in the QR-Code:
> 3. Separate the manufacturerer address on the nameplate optically as indicated here
> 4. Do not print the idShort on the nameplate
> 5. Do not print marking texts and the marking icons simultaneously on the nameplate
