### ISSUE TITLE
Questions: Use cases and Requirements

### ISSUE THREAD

**Issue by ErikaZha** [mk28/TINF21C_Team2_AAS_digital_nameplate#35]
Dear Customer (@mrentsch65),

we are currently in the process of creating the CRS and SRS and would like to know your opinion on the following use cases and requirements.

Use Cases:
-	Search for a Server
-	Search for an asset
-	Select and view an asset
-	View nameplate preview
-	Download in PNG format
-	Download in SVG format

Requirements:
-	Graphical user interface (GUI) components
-	Responsive and compatible GUI
-	Navigation Button such as the back button
-	Dark and light mode Buttons 
-	Search functions
-	Asset selection
-	QR-code generator
-	Download buttons for PNG and SVG format
-	nameplate generator
-	nameplate preview (When the user clicks on this a bigger version of the nameplate will appear and fill the user’s screen)
-	testing
-	error handling 

Non-functional Requirements:
-	User-friendly
-	License
-	Performance
-	Reliability
-	Maintainability

We would like to know if all of these are correct and whether you have more use cases and requirements in mind? These are the use cases and requirements that our System Architect and Software Developer composed in cooperation with the documents you provided.
We appreciate your help and are looking forward to your answer! Our goal is to create a high-quality which will surpass your expectations. 

Kind Regards,
Adrian Khairi and Erika Zhang in the name of Team 2

**Comment by mrentsch65** [comment]
I would see the following as relevant:

**Use Cases:**

- Manage a number of servers
- Search for an asset on the servers
   ALTERNATIVELY
    - Select a Server
    - Browse the Server
- Select and view an asset
- View nameplate preview
- Download in PNG format
- Download in SVG format

**Requirements:**

- Responsive and compatible GUI  
- Dark and light mode menu
- Download menu for PNG and SVG format
- Search functionality
    - Navigation Buttons
- QR-code generator
- nameplate generator
- nameplate preview (When the user clicks on this a bigger version of the nameplate will appear and fill the user’s screen)
- error handling

**Non-functional Requirements:**

- User-friendly
- Performance
- Reliability
- Maintainability
- License

**Comment by ErikaZha** [comment]
Dear Customer (@mrentsch),

We have a few questions regarding your answer. 
1.	Could you please elaborate the use case “Managing a number of servers”? 
2.	Is there any reason why the navigation buttons are a sub point of the requirement “Search functionality”? Should it be treated as such or are we allowed to write it as a separate requirement?
3.	Additionally, what do you define as navigation buttons? Our team decided to only implement the back button since the forward button isn’t really needed, however, would you like a forward and back button or is the back button just fine? 

Thank you in advance!
