### ISSUE TITLE
Questions: QR-code margin

### ISSUE THREAD

**Issue by ErikaZha** [mk28/TINF21C_Team2_AAS_digital_nameplate#36]
Dear Customer (@mrentsch65),

In the print manuscript, the sample QR codes from the nameplates do not have a border. In Chapter 8.1.4 of the print manuscript, a reference is made to the DIN 91406 with regard to the module width of the QR code. It states that a QR code should also have a margin (see Figure 6). Do the QR codes on the digital nameplates require this margin?

Kind Regards,
Adrian Khairi and Erika Zhang in the name of Team 2

**Comment by mrentsch65** [comment]
I recommend a margin.

**Comment by mk28** [comment]
Dear Customer,

we realized our last question was not accurate enough. The point of the question was not only the margin of the QR-Code, but also the Border for QR-Codes specified in DIN 91406 which is referenced by the Nameplate spec. This border is not shown in the exaple image of the nameplate spec.
![grafik](https://user-images.githubusercontent.com/32399022/195770277-3cda1c1f-d02e-4b64-9b58-4294e03739fe.png)
![grafik](https://user-images.githubusercontent.com/32399022/195770548-5ac9c24a-647f-4610-8267-cfd2e60cd8b7.png)

**Comment by AdrianKhairi** [comment]
Customer stated the border is not necessary. But a certain distance to other elements of the nameplates is recommended.
