### ISSUE TITLE
Agreement on decisions from meeting on 14.10.2022

### ISSUE THREAD

**Issue by mariskoch** [mk28/TINF21C_Team2_AAS_digital_nameplate#42]
Dear customer (@mrentsch65),

these are the decisions from the meeting on the 14.10.2022 in the DHBW. I would ask you to read through them and give written approval to them in form of a comment.

1. If an asset does not contain all the necessary information for a nameplate, the nameplate will still be generated but with that part of information missing. E.g. if an asset does not contain the serial number, batch number and product country of origin, the nameplate will be generated but without these information on it.
2. In the screen, where the nameplate will be available for download for the user, we will supply a choice-functionality, whether the QR-Code contains all the information specified by [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild [pp. 6-7]](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397) or just the link referring to the asset information by the manufacturer. The user has to decide whether he wants the full information in the QR-Code or just the link. The decision will not be made automatically.
3. The feature, that there will be automatically only the markings corresponding to the market of the user on the nameplate (e.g. CE-marking in Europe), is not mandatory.
4. Pre-generated QR-Codes and namepaltes from assets will not be used. An example can be seen at [R.Stahl, 8570/11-506 WA 200/346-240/415V, 50/60Hz](https://demo-digital-twin.r-stahl.com/x999999999x044?lang=de) under "Identification (Human View)" at the very bottom. QR-Codes and namepaltes like these will not be used.
5. A border and padding to the QR-Code on the namepalte is not mandatory. This answers the ticket #36. We will orient our namepaltes around the example from [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild [p. 8]](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397).
6. The safety instructions for safe use specified in [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild, chapter 6.2](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397) will not be included in the nameplate. Reason for that is, that the norm by the IDTA is still in review. That means that these information can not be extracted systematically from the asset.

**Comment by mrentsch65** [comment]
> 1. If an asset does not contain all the necessary information for a nameplate, the nameplate will still be generated but with that part of information missing. E.g. if an asset does not contain the serial number, batch number and product country of origin, the nameplate will be generated but without these information on it.
>> Yes

> 2. In the screen, where the nameplate will be available for download for the user, we will supply a choice-functionality, whether the QR-Code contains all the information specified by [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild [pp. 6-7]](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397) or just the link referring to the asset information by the manufacturer. The user has to decide whether he wants the full information in the QR-Code or just the link. The decision will not be made automatically.
>> Yes, but default shall be full information.

> 3. The feature, that there will be automatically only the markings corresponding to the market of the user on the nameplate (e.g. CE-marking in Europe), is not mandatory.
>> Yes, this feature shall be optional.

> 4. Pre-generated QR-Codes and namepaltes from assets will not be used. An example can be seen at [R.Stahl, 8570/11-506 WA 200/346-240/415V, 50/60Hz](https://demo-digital-twin.r-stahl.com/x999999999x044?lang=de) under "Identification (Human View)" at the very bottom. QR-Codes and namepaltes like these will not be used.
>> Yes, do not use these images.

> 5. A border and padding to the QR-Code on the namepalte is not mandatory. This answers the ticket [Questions: QR-code margin #36](https://github.com/mk28/TINF21C_Team2_AAS_digital_nameplate/issues/36). We will orient our namepaltes around the example from [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild [p. 8]](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397).
>> Yes

> 6. The safety instructions for safe use specified in [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild, chapter 6.2](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397) will not be included in the nameplate. Reason for that is, that the norm by the IDTA is still in review. That means that these information can not be extracted systematically from the asset.
>> Yes
