### ISSUE TITLE
Systematically identifying information in assets

### ISSUE THREAD

**Issue by mariskoch** [mk28/TINF21C_Team2_AAS_digital_nameplate#43]
Dear customer (@mrentsch65),

concluding from the meeting on the 14.10.2022 in the DHBW, I will post the resulting questions here. I would ask you to answer them in form of a comment.

1. How do we systematically identify the **markings** from the response of an AAS-Server for an asset? This requirement arises from [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild, chapter 6.3](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397). 
2. How do we systematically identify, whether an asset belongs in the category of **electrical equipment**? This requirement arises from [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild, chapter 6.4](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397). Resulting from that, how do we systematically find the relevant specific electrical information for that asset specified in [chapter 6.4](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397)?
3. How do we systematically identify, whether an asset belongs in the category of **explosive-proof devices**? This requirement arises from [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild, chapter 6.5](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397). Resulting from that, how do we systematically find the relevant specific explosive-proof information for that asset specified in [chapter 6.5](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397)?
4. How do we systematically identify, whether an asset belongs in the category of **pressure devices**? This requirement arises from [241-0-25_2020-0016_Druckmanuskript_Digitales_Typenschild, chapter 6.6](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397). Resulting from that, how do we systematically find the relevant specific pressure-related information for that asset specified in [chapter 6.6](https://nextcloud.dhbw-stuttgart.de/index.php/s/KsiysmztfR6dzYj?dir=undefined&openfile=23075397)?

**Comment by mrentsch65** [comment]
Please find here the newest draf  of the AAS-Submodel "Digital Nameplate", where some of your questions should be answered:  https://nextcloud.dhbw-stuttgart.de/index.php/s/7wEBqdMYBmCCpiG

**Comment by mrentsch65** [comment]
Dear Team,
regarding usability improvement, I propose to adjust the display of the markings as follows by not showing the too technical content:

![image](https://user-images.githubusercontent.com/50681355/232200771-146911e2-8355-4a54-8199-3d5c06df40bb.png)

**Comment by mrentsch65** [comment]
Please make links always clickable to be opened in another browser tab, i.e.:

![image](https://user-images.githubusercontent.com/50681355/232200904-a4789fef-d346-46ed-8184-d93cb1c423f7.png)

**Comment by mrentsch65** [comment]
When no namplate data could found in the ASS, can you additionaly print to some high-level-extent what actually is inside the AAS?

![image](https://user-images.githubusercontent.com/50681355/232201057-c2f1c1bc-0c68-4c02-ab07-85a557034d6f.png)
