### ISSUE TITLE
Document Review

### ISSUE THREAD

**Issue by ErikaZha** [mk28/TINF21C_Team2_AAS_digital_nameplate#55]
Dear Customer (@mrentsch65),

we have published our documents including BC, CRS, PSP, SRS and SAS in the GitHub folder [PROJECT](https://github.com/mk28/TINF21C_Team2_AAS_digital_nameplate/tree/main/PROJECT) and would like to know your opinion on the documents. As we have not discussed the SAS with you in person I would like to ask you to please review the SAS in more detail.

Note that the SAS and SRS will also be added to the GitHub Wiki once we have received your review and improved the documents.

We appreciate your help and are looking forward to your answer as our goal is to create a high-quality product with the documents as our basis. 

Kind Regards,
Erika Zhang in the name of Team 2

**Comment by mrentsch65** [comment]
I had a look into your SAS and the following feedback:

1. "Usability" is not an architectural subject, please deal with it in the SRS, not the SAS.
2. "Source Code Organization" of the project is completely missing.
3. "Architecture Compliance Review": This is in my opinion not  needed.
