### ISSUE TITLE
Research open source license

### ISSUE THREAD

**Issue by mk28** [mk28/TINF21C_Team2_AAS_digital_nameplate#6]
Find an open source licesne best suited for the project.
Specifically the licenses GitHub offers templates for.

- Present results to team

**Comment by NxtShay** [comment]
**Types of licenses:** 

- Permissive: free to use, modify and re-distribute while permitting proprietary derivative works
- Copyleft: grant user access to source code, derivative work must have the same license
- Weak Copyleft: between permissive and copyleft, copyleft only applies on specifc components
- Copyright: need exclusive rights from the publisher

**Licenses offered by Git Hub:**

- Apache: permissive, patent rights
- GNU v3.0: copyleft, no changing
- MIT: permissive, only 2 conditions: notice in product and do not sue the author
- BSD 2 equals MIT
- BSD 3 has one additional clause: it does not allow to promote products using the name of the copyright holders or contributers
- Boost: permissive
- CCO: copyright
- Eclipse: copyleft
- GNU Affero: strongest copyleft, no changing
- GNU v2.0: most widely used, strong copyleft, no changing
- GNU Lesser: copyleft, primarily used for software libraries, derived works that only link to it do not have the restriction to have the same license, no changing
- Mozilla: weak copyleft
- The Unlicense: no conditions, just for the copyright laws

**Comment by NxtShay** [comment]
We chose the permissive license MIT.
