### ISSUE TITLE
Newest AAS V3 available

### ISSUE THREAD

**Issue by mrentsch65** [mk28/TINF21C_Team2_AAS_digital_nameplate#63]
Find here the newest developments from the standardization group:

https://v3.admin-shell-io.com/swagger/index.html

https://v3.admin-shell-io.com/

I advise you to adjust to this recent work in your project.

**Comment by mk28** [comment]
Dear Customer,

the V3 API is now implemented on Branch [update_api_v3](https://github.com/mk28/TINF21C_Team2_AAS_digital_nameplate/tree/update_api_v3).
It is currently not usable with any online AAS servers, known to us, as they either do not support the V3 spec or do not implement CORS. The website <https://v3.admin-shell-io.com/> also does not implement CORS which makes requests from our service not possible. This is a server side issue and not something we can fix in our code. 

We use a locally modified version of their server, that provides CORS, for our testing.

**Comment by mrentsch65** [comment]
Hello,
when I for example call https://v3.admin-shell-io.com/shells in my browser, a large data object listing the AAS entries is returned.  Why is this not working in your setup?

**Comment by mrentsch65** [comment]
When I call our application with a server address like this one:
https://mk28.github.io/TINF21C_Team2_AAS_digital_nameplate/#/list?server=https://v3.admin-shell-io.com/, I can observe that your application is still calling the endpoint "https://v3.admin-shell-io.com/listaas" instead of "https://v3.admin-shell-io.com/shells" This is in my observation the initial problem!

**Comment by mk28** [comment]
Dear Customer,

the Reason the requests via your browser work is that they are not cross platform and thus are not blocked by the server. 
I deployed the new version of the programm to <https://mk28.github.io/TINF21C_Team2_AAS_digital_nameplate/#/home> it uses multiple endpoints defined in the [Swagger Documentation](https://v3.admin-shell-io.com/swagger/index.html). One of them being the `/submodels` endpoint and one being the `/shells` endpoint.

The Server of adminshell-io does not allow requests from our service as the server responses are missing a header and the browser itself does not allow requests without this header.
![grafik](https://user-images.githubusercontent.com/32399022/213909381-27b4410c-6d67-4bd5-afa2-f647ba4ee467.png)
This is nothing we can fix on our end, but a problem with the server of adminshell-io. The missing header triggers a security feature that is present in basically all modern browsers.
We use a locally modified and built version of the server found at <https://github.com/admin-shell-io/aasx-server/tree/masterV3> for our development and testing. This local copy does provide the missing header. It is not available online.

We are not waware of any other online resources that provide a v3 compatible API that also supplies the missing header.

**Comment by mrentsch65** [comment]
Your call on 'https://v3.admin-shell-io.com/submodels' out of the REACT App as client gets ansered from the server with as status code OK (200), but does not deliver a response object. In the HTTP request header, the following content is present:
```
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
```
When called directly from my browser (where I get a response object back), the HTTP request header contains the following:
```
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
```
Thus to me it seems that it is a configuration issue within the REACT App.

**Comment by mk28** [comment]
Dear Customer,

the headers you are mentioning have nothing to do the CORS behavior of our service.
The status 200 can be returned as the request is answered by the server and the answer also contains all relevant content. But as the `Access-Control-Allow-Origin` header is not present, the browser does not forward the answer to the scripts of our service. This is a feature in almost all modern browsers. You can learn more about CORS [here](https://javascript.info/fetch-crossorigin).

- `Sec-Fetch-Dest: empty` means that this request was sent by a script. In our case the fetch() command
- `Sec-Fetch-Dest: document` means that this request was originated by user navigation i.e. typing the address in the address bar of the browser. More info [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Dest)

- `Sec-Fetch-Mode: cors` means that the origin of the request is from another website than the destination of the request. I.e. our service hosted on github is on another host than the server hosted by adminshell io, This also signals the server that the request uses the CORS protocol. 
- `Sec-Fetch-Mode: navigate` means that the request was triggered my a navigation between HTML documents. In this case the navigation via the address bar of the browser More info [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Mode)

- `Sec-Fetch-Site: cross-site` indicates what kind of request is sent. `cross-site` indicates that sender and receiver have different hosts. 
- `Sec-Fetch-Site: none` indicates that the request is user originated. Learn more [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site)

None of these headers should have any influence on the return headers or the behavior of the browser. These headers are set to better inform the server of the origin of a request and as metadata should allow the server to decide, if a host is allowed to access a specific resource. 

As the server answers our request with a status code 200 the server does not deny the use of the resources. But as the  `Access-Control-Allow-Origin` header is not set in the response, the browser i.e. Chrome, Edge, Safari or Firefox block the incoming data as a security measure. 
There is no configuration in our app that could prevent this behavior of the browser as it is intended as a security measure. 

It could be possible to work around the issue with a proxy, but this neither a good solution nor does it fix the actual problem

**Comment by mrentsch65** [comment]
Ok, in this case I recommend you to contact the [maintainers of admin-shell-io.com](https://v3.admin-shell-io.com/About) via eMail and point them to this problem.
