### ISSUE TITLE
Problem with German Umlauts

### ISSUE THREAD

**Issue by mariskoch** [mk28/TINF21C_Team2_AAS_digital_nameplate#96]
The German characters `ä`, `ö`, `ü`, `ß` seem to be broken in some assets.

### Example

All examples refer to the `idShort` of the asset.

1. From Asset `ARGO_HYTOS_Return_Filter_ES075`:
```json
{
  "nameplate": {
    "ManufacturerProductDesignation": "Saugfilter fÃ¼r Tankeinbau - Anschluss G1 - Nennvolumenstrom 45 lpm / 11,9 gpm"
  }
}
```
2. From Asset `AAS_Type_SPAU-P10R-T-G18M-L-PNLK-PNVBA-M8D`:

In the middle, after the word "Druckabfrage", I am not even sure if this is an umlaut or something else that is broken. I can not identify what it is supposed to be.

```json
{
  "nameplate": {
    "ManufacturerProductDesignation": "Einzigartig flexibel im Anschluss: der Drucksensor SPAU. Ob Druckmessung, DruckÃ¼berwachung oder Druckabfrage â�� Sie haben alle Druckwerte immer auf einen Blick unter Kontrolle. Im IO-Link-Mode sind Fernwartung und -parametrierung sowie eine einfache Sensorenreplizierung mÃ¶glich."
  }
}
```
4. From Asset `Festo_3S7PM0CP4BD`
```json
{
  "nameplate":  {
    "PhysicalAddress": {
      "StateCounty": "Baden-WÃ¼rttemberg"
    }
  }  
}
```

### Acceptance Criteria

The umlauts are depicted correctly in the ui and on the nameplates.

**Comment by mariskoch** [comment]
### Important Update

The umlaut error in example 2 after the word "Druckabfrage" seems to be that sever, that it even breaks the qr-code. The generated qr-code of this asset can not be scanned. I have the theory that this is the case, because the broken characters are not supported by the qr-code standard or library.

**Comment by mk28** [comment]
This Issue resoved itself. It seems to have been a copy-paste mistake.
